// Code generated by counterfeiter. DO NOT EDIT.
package linearfakes

import (
	"context"
	"sync"

	"github.com/pmenglund/colin/internal/linear"
)

type FakeClient struct {
	GetIssueStub        func(context.Context, string) (linear.Issue, error)
	getIssueMutex       sync.RWMutex
	getIssueArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getIssueReturns struct {
		result1 linear.Issue
		result2 error
	}
	getIssueReturnsOnCall map[int]struct {
		result1 linear.Issue
		result2 error
	}
	ListCandidateIssuesStub        func(context.Context, string) ([]linear.Issue, error)
	listCandidateIssuesMutex       sync.RWMutex
	listCandidateIssuesArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listCandidateIssuesReturns struct {
		result1 []linear.Issue
		result2 error
	}
	listCandidateIssuesReturnsOnCall map[int]struct {
		result1 []linear.Issue
		result2 error
	}
	UpdateIssueMetadataStub        func(context.Context, string, linear.MetadataPatch) error
	updateIssueMetadataMutex       sync.RWMutex
	updateIssueMetadataArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 linear.MetadataPatch
	}
	updateIssueMetadataReturns struct {
		result1 error
	}
	updateIssueMetadataReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateIssueStateStub        func(context.Context, string, string) error
	updateIssueStateMutex       sync.RWMutex
	updateIssueStateArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	updateIssueStateReturns struct {
		result1 error
	}
	updateIssueStateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) GetIssue(arg1 context.Context, arg2 string) (linear.Issue, error) {
	fake.getIssueMutex.Lock()
	ret, specificReturn := fake.getIssueReturnsOnCall[len(fake.getIssueArgsForCall)]
	fake.getIssueArgsForCall = append(fake.getIssueArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetIssueStub
	fakeReturns := fake.getIssueReturns
	fake.recordInvocation("GetIssue", []interface{}{arg1, arg2})
	fake.getIssueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetIssueCallCount() int {
	fake.getIssueMutex.RLock()
	defer fake.getIssueMutex.RUnlock()
	return len(fake.getIssueArgsForCall)
}

func (fake *FakeClient) GetIssueCalls(stub func(context.Context, string) (linear.Issue, error)) {
	fake.getIssueMutex.Lock()
	defer fake.getIssueMutex.Unlock()
	fake.GetIssueStub = stub
}

func (fake *FakeClient) GetIssueArgsForCall(i int) (context.Context, string) {
	fake.getIssueMutex.RLock()
	defer fake.getIssueMutex.RUnlock()
	argsForCall := fake.getIssueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) GetIssueReturns(result1 linear.Issue, result2 error) {
	fake.getIssueMutex.Lock()
	defer fake.getIssueMutex.Unlock()
	fake.GetIssueStub = nil
	fake.getIssueReturns = struct {
		result1 linear.Issue
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetIssueReturnsOnCall(i int, result1 linear.Issue, result2 error) {
	fake.getIssueMutex.Lock()
	defer fake.getIssueMutex.Unlock()
	fake.GetIssueStub = nil
	if fake.getIssueReturnsOnCall == nil {
		fake.getIssueReturnsOnCall = make(map[int]struct {
			result1 linear.Issue
			result2 error
		})
	}
	fake.getIssueReturnsOnCall[i] = struct {
		result1 linear.Issue
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListCandidateIssues(arg1 context.Context, arg2 string) ([]linear.Issue, error) {
	fake.listCandidateIssuesMutex.Lock()
	ret, specificReturn := fake.listCandidateIssuesReturnsOnCall[len(fake.listCandidateIssuesArgsForCall)]
	fake.listCandidateIssuesArgsForCall = append(fake.listCandidateIssuesArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListCandidateIssuesStub
	fakeReturns := fake.listCandidateIssuesReturns
	fake.recordInvocation("ListCandidateIssues", []interface{}{arg1, arg2})
	fake.listCandidateIssuesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListCandidateIssuesCallCount() int {
	fake.listCandidateIssuesMutex.RLock()
	defer fake.listCandidateIssuesMutex.RUnlock()
	return len(fake.listCandidateIssuesArgsForCall)
}

func (fake *FakeClient) ListCandidateIssuesCalls(stub func(context.Context, string) ([]linear.Issue, error)) {
	fake.listCandidateIssuesMutex.Lock()
	defer fake.listCandidateIssuesMutex.Unlock()
	fake.ListCandidateIssuesStub = stub
}

func (fake *FakeClient) ListCandidateIssuesArgsForCall(i int) (context.Context, string) {
	fake.listCandidateIssuesMutex.RLock()
	defer fake.listCandidateIssuesMutex.RUnlock()
	argsForCall := fake.listCandidateIssuesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) ListCandidateIssuesReturns(result1 []linear.Issue, result2 error) {
	fake.listCandidateIssuesMutex.Lock()
	defer fake.listCandidateIssuesMutex.Unlock()
	fake.ListCandidateIssuesStub = nil
	fake.listCandidateIssuesReturns = struct {
		result1 []linear.Issue
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListCandidateIssuesReturnsOnCall(i int, result1 []linear.Issue, result2 error) {
	fake.listCandidateIssuesMutex.Lock()
	defer fake.listCandidateIssuesMutex.Unlock()
	fake.ListCandidateIssuesStub = nil
	if fake.listCandidateIssuesReturnsOnCall == nil {
		fake.listCandidateIssuesReturnsOnCall = make(map[int]struct {
			result1 []linear.Issue
			result2 error
		})
	}
	fake.listCandidateIssuesReturnsOnCall[i] = struct {
		result1 []linear.Issue
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) UpdateIssueMetadata(arg1 context.Context, arg2 string, arg3 linear.MetadataPatch) error {
	fake.updateIssueMetadataMutex.Lock()
	ret, specificReturn := fake.updateIssueMetadataReturnsOnCall[len(fake.updateIssueMetadataArgsForCall)]
	fake.updateIssueMetadataArgsForCall = append(fake.updateIssueMetadataArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 linear.MetadataPatch
	}{arg1, arg2, arg3})
	stub := fake.UpdateIssueMetadataStub
	fakeReturns := fake.updateIssueMetadataReturns
	fake.recordInvocation("UpdateIssueMetadata", []interface{}{arg1, arg2, arg3})
	fake.updateIssueMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) UpdateIssueMetadataCallCount() int {
	fake.updateIssueMetadataMutex.RLock()
	defer fake.updateIssueMetadataMutex.RUnlock()
	return len(fake.updateIssueMetadataArgsForCall)
}

func (fake *FakeClient) UpdateIssueMetadataCalls(stub func(context.Context, string, linear.MetadataPatch) error) {
	fake.updateIssueMetadataMutex.Lock()
	defer fake.updateIssueMetadataMutex.Unlock()
	fake.UpdateIssueMetadataStub = stub
}

func (fake *FakeClient) UpdateIssueMetadataArgsForCall(i int) (context.Context, string, linear.MetadataPatch) {
	fake.updateIssueMetadataMutex.RLock()
	defer fake.updateIssueMetadataMutex.RUnlock()
	argsForCall := fake.updateIssueMetadataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) UpdateIssueMetadataReturns(result1 error) {
	fake.updateIssueMetadataMutex.Lock()
	defer fake.updateIssueMetadataMutex.Unlock()
	fake.UpdateIssueMetadataStub = nil
	fake.updateIssueMetadataReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) UpdateIssueMetadataReturnsOnCall(i int, result1 error) {
	fake.updateIssueMetadataMutex.Lock()
	defer fake.updateIssueMetadataMutex.Unlock()
	fake.UpdateIssueMetadataStub = nil
	if fake.updateIssueMetadataReturnsOnCall == nil {
		fake.updateIssueMetadataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateIssueMetadataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) UpdateIssueState(arg1 context.Context, arg2 string, arg3 string) error {
	fake.updateIssueStateMutex.Lock()
	ret, specificReturn := fake.updateIssueStateReturnsOnCall[len(fake.updateIssueStateArgsForCall)]
	fake.updateIssueStateArgsForCall = append(fake.updateIssueStateArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.UpdateIssueStateStub
	fakeReturns := fake.updateIssueStateReturns
	fake.recordInvocation("UpdateIssueState", []interface{}{arg1, arg2, arg3})
	fake.updateIssueStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) UpdateIssueStateCallCount() int {
	fake.updateIssueStateMutex.RLock()
	defer fake.updateIssueStateMutex.RUnlock()
	return len(fake.updateIssueStateArgsForCall)
}

func (fake *FakeClient) UpdateIssueStateCalls(stub func(context.Context, string, string) error) {
	fake.updateIssueStateMutex.Lock()
	defer fake.updateIssueStateMutex.Unlock()
	fake.UpdateIssueStateStub = stub
}

func (fake *FakeClient) UpdateIssueStateArgsForCall(i int) (context.Context, string, string) {
	fake.updateIssueStateMutex.RLock()
	defer fake.updateIssueStateMutex.RUnlock()
	argsForCall := fake.updateIssueStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeClient) UpdateIssueStateReturns(result1 error) {
	fake.updateIssueStateMutex.Lock()
	defer fake.updateIssueStateMutex.Unlock()
	fake.UpdateIssueStateStub = nil
	fake.updateIssueStateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) UpdateIssueStateReturnsOnCall(i int, result1 error) {
	fake.updateIssueStateMutex.Lock()
	defer fake.updateIssueStateMutex.Unlock()
	fake.UpdateIssueStateStub = nil
	if fake.updateIssueStateReturnsOnCall == nil {
		fake.updateIssueStateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateIssueStateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ linear.Client = new(FakeClient)
