// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/pmenglund/colin/internal/repohost"
	"github.com/pmenglund/colin/internal/repoops"
)

type FakeRepoHostClient struct {
	BranchExistsStub        func(context.Context, string, string, string) (bool, error)
	branchExistsMutex       sync.RWMutex
	branchExistsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	branchExistsReturns struct {
		result1 bool
		result2 error
	}
	branchExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	CreatePullRequestStub        func(context.Context, string, string, repohost.CreatePullRequestInput) (*repohost.PullRequest, error)
	createPullRequestMutex       sync.RWMutex
	createPullRequestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 repohost.CreatePullRequestInput
	}
	createPullRequestReturns struct {
		result1 *repohost.PullRequest
		result2 error
	}
	createPullRequestReturnsOnCall map[int]struct {
		result1 *repohost.PullRequest
		result2 error
	}
	MergePullRequestStub        func(context.Context, string, string, int, string) error
	mergePullRequestMutex       sync.RWMutex
	mergePullRequestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	mergePullRequestReturns struct {
		result1 error
	}
	mergePullRequestReturnsOnCall map[int]struct {
		result1 error
	}
	PullRequestByHeadStub        func(context.Context, string, string, string, string) (*repohost.PullRequest, error)
	pullRequestByHeadMutex       sync.RWMutex
	pullRequestByHeadArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	pullRequestByHeadReturns struct {
		result1 *repohost.PullRequest
		result2 error
	}
	pullRequestByHeadReturnsOnCall map[int]struct {
		result1 *repohost.PullRequest
		result2 error
	}
	PullRequestByNumberStub        func(context.Context, string, string, int) (*repohost.PullRequest, error)
	pullRequestByNumberMutex       sync.RWMutex
	pullRequestByNumberArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	pullRequestByNumberReturns struct {
		result1 *repohost.PullRequest
		result2 error
	}
	pullRequestByNumberReturnsOnCall map[int]struct {
		result1 *repohost.PullRequest
		result2 error
	}
	PullRequestChecksStub        func(context.Context, string, string, int) (repohost.PullRequestCheckRollup, error)
	pullRequestChecksMutex       sync.RWMutex
	pullRequestChecksArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	pullRequestChecksReturns struct {
		result1 repohost.PullRequestCheckRollup
		result2 error
	}
	pullRequestChecksReturnsOnCall map[int]struct {
		result1 repohost.PullRequestCheckRollup
		result2 error
	}
	PullRequestReactionsStub        func(context.Context, string, string, int, string) (repohost.ReactionPage, error)
	pullRequestReactionsMutex       sync.RWMutex
	pullRequestReactionsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	pullRequestReactionsReturns struct {
		result1 repohost.ReactionPage
		result2 error
	}
	pullRequestReactionsReturnsOnCall map[int]struct {
		result1 repohost.ReactionPage
		result2 error
	}
	PullRequestReviewCommentReactionsStub        func(context.Context, string, string, int64, int) (repohost.ReviewCommentReactionPage, error)
	pullRequestReviewCommentReactionsMutex       sync.RWMutex
	pullRequestReviewCommentReactionsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int64
		arg5 int
	}
	pullRequestReviewCommentReactionsReturns struct {
		result1 repohost.ReviewCommentReactionPage
		result2 error
	}
	pullRequestReviewCommentReactionsReturnsOnCall map[int]struct {
		result1 repohost.ReviewCommentReactionPage
		result2 error
	}
	ReplyToReviewThreadStub        func(context.Context, string, string) error
	replyToReviewThreadMutex       sync.RWMutex
	replyToReviewThreadArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	replyToReviewThreadReturns struct {
		result1 error
	}
	replyToReviewThreadReturnsOnCall map[int]struct {
		result1 error
	}
	ResolveReviewThreadStub        func(context.Context, string) error
	resolveReviewThreadMutex       sync.RWMutex
	resolveReviewThreadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	resolveReviewThreadReturns struct {
		result1 error
	}
	resolveReviewThreadReturnsOnCall map[int]struct {
		result1 error
	}
	ReviewThreadCommentsStub        func(context.Context, string, string) (repohost.ReviewThreadCommentPage, error)
	reviewThreadCommentsMutex       sync.RWMutex
	reviewThreadCommentsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	reviewThreadCommentsReturns struct {
		result1 repohost.ReviewThreadCommentPage
		result2 error
	}
	reviewThreadCommentsReturnsOnCall map[int]struct {
		result1 repohost.ReviewThreadCommentPage
		result2 error
	}
	ReviewThreadsStub        func(context.Context, string, string, int, string) (repohost.ReviewThreadPage, error)
	reviewThreadsMutex       sync.RWMutex
	reviewThreadsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	reviewThreadsReturns struct {
		result1 repohost.ReviewThreadPage
		result2 error
	}
	reviewThreadsReturnsOnCall map[int]struct {
		result1 repohost.ReviewThreadPage
		result2 error
	}
	ValidateAuthStub        func(context.Context) error
	validateAuthMutex       sync.RWMutex
	validateAuthArgsForCall []struct {
		arg1 context.Context
	}
	validateAuthReturns struct {
		result1 error
	}
	validateAuthReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRepoHostClient) BranchExists(arg1 context.Context, arg2 string, arg3 string, arg4 string) (bool, error) {
	fake.branchExistsMutex.Lock()
	ret, specificReturn := fake.branchExistsReturnsOnCall[len(fake.branchExistsArgsForCall)]
	fake.branchExistsArgsForCall = append(fake.branchExistsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.BranchExistsStub
	fakeReturns := fake.branchExistsReturns
	fake.recordInvocation("BranchExists", []interface{}{arg1, arg2, arg3, arg4})
	fake.branchExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) BranchExistsCallCount() int {
	fake.branchExistsMutex.RLock()
	defer fake.branchExistsMutex.RUnlock()
	return len(fake.branchExistsArgsForCall)
}

func (fake *FakeRepoHostClient) BranchExistsCalls(stub func(context.Context, string, string, string) (bool, error)) {
	fake.branchExistsMutex.Lock()
	defer fake.branchExistsMutex.Unlock()
	fake.BranchExistsStub = stub
}

func (fake *FakeRepoHostClient) BranchExistsArgsForCall(i int) (context.Context, string, string, string) {
	fake.branchExistsMutex.RLock()
	defer fake.branchExistsMutex.RUnlock()
	argsForCall := fake.branchExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRepoHostClient) BranchExistsReturns(result1 bool, result2 error) {
	fake.branchExistsMutex.Lock()
	defer fake.branchExistsMutex.Unlock()
	fake.BranchExistsStub = nil
	fake.branchExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) BranchExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.branchExistsMutex.Lock()
	defer fake.branchExistsMutex.Unlock()
	fake.BranchExistsStub = nil
	if fake.branchExistsReturnsOnCall == nil {
		fake.branchExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.branchExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) CreatePullRequest(arg1 context.Context, arg2 string, arg3 string, arg4 repohost.CreatePullRequestInput) (*repohost.PullRequest, error) {
	fake.createPullRequestMutex.Lock()
	ret, specificReturn := fake.createPullRequestReturnsOnCall[len(fake.createPullRequestArgsForCall)]
	fake.createPullRequestArgsForCall = append(fake.createPullRequestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 repohost.CreatePullRequestInput
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreatePullRequestStub
	fakeReturns := fake.createPullRequestReturns
	fake.recordInvocation("CreatePullRequest", []interface{}{arg1, arg2, arg3, arg4})
	fake.createPullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) CreatePullRequestCallCount() int {
	fake.createPullRequestMutex.RLock()
	defer fake.createPullRequestMutex.RUnlock()
	return len(fake.createPullRequestArgsForCall)
}

func (fake *FakeRepoHostClient) CreatePullRequestCalls(stub func(context.Context, string, string, repohost.CreatePullRequestInput) (*repohost.PullRequest, error)) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = stub
}

func (fake *FakeRepoHostClient) CreatePullRequestArgsForCall(i int) (context.Context, string, string, repohost.CreatePullRequestInput) {
	fake.createPullRequestMutex.RLock()
	defer fake.createPullRequestMutex.RUnlock()
	argsForCall := fake.createPullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRepoHostClient) CreatePullRequestReturns(result1 *repohost.PullRequest, result2 error) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = nil
	fake.createPullRequestReturns = struct {
		result1 *repohost.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) CreatePullRequestReturnsOnCall(i int, result1 *repohost.PullRequest, result2 error) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = nil
	if fake.createPullRequestReturnsOnCall == nil {
		fake.createPullRequestReturnsOnCall = make(map[int]struct {
			result1 *repohost.PullRequest
			result2 error
		})
	}
	fake.createPullRequestReturnsOnCall[i] = struct {
		result1 *repohost.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) MergePullRequest(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) error {
	fake.mergePullRequestMutex.Lock()
	ret, specificReturn := fake.mergePullRequestReturnsOnCall[len(fake.mergePullRequestArgsForCall)]
	fake.mergePullRequestArgsForCall = append(fake.mergePullRequestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.MergePullRequestStub
	fakeReturns := fake.mergePullRequestReturns
	fake.recordInvocation("MergePullRequest", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.mergePullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepoHostClient) MergePullRequestCallCount() int {
	fake.mergePullRequestMutex.RLock()
	defer fake.mergePullRequestMutex.RUnlock()
	return len(fake.mergePullRequestArgsForCall)
}

func (fake *FakeRepoHostClient) MergePullRequestCalls(stub func(context.Context, string, string, int, string) error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = stub
}

func (fake *FakeRepoHostClient) MergePullRequestArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.mergePullRequestMutex.RLock()
	defer fake.mergePullRequestMutex.RUnlock()
	argsForCall := fake.mergePullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeRepoHostClient) MergePullRequestReturns(result1 error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = nil
	fake.mergePullRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) MergePullRequestReturnsOnCall(i int, result1 error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = nil
	if fake.mergePullRequestReturnsOnCall == nil {
		fake.mergePullRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.mergePullRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) PullRequestByHead(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) (*repohost.PullRequest, error) {
	fake.pullRequestByHeadMutex.Lock()
	ret, specificReturn := fake.pullRequestByHeadReturnsOnCall[len(fake.pullRequestByHeadArgsForCall)]
	fake.pullRequestByHeadArgsForCall = append(fake.pullRequestByHeadArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PullRequestByHeadStub
	fakeReturns := fake.pullRequestByHeadReturns
	fake.recordInvocation("PullRequestByHead", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.pullRequestByHeadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) PullRequestByHeadCallCount() int {
	fake.pullRequestByHeadMutex.RLock()
	defer fake.pullRequestByHeadMutex.RUnlock()
	return len(fake.pullRequestByHeadArgsForCall)
}

func (fake *FakeRepoHostClient) PullRequestByHeadCalls(stub func(context.Context, string, string, string, string) (*repohost.PullRequest, error)) {
	fake.pullRequestByHeadMutex.Lock()
	defer fake.pullRequestByHeadMutex.Unlock()
	fake.PullRequestByHeadStub = stub
}

func (fake *FakeRepoHostClient) PullRequestByHeadArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.pullRequestByHeadMutex.RLock()
	defer fake.pullRequestByHeadMutex.RUnlock()
	argsForCall := fake.pullRequestByHeadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeRepoHostClient) PullRequestByHeadReturns(result1 *repohost.PullRequest, result2 error) {
	fake.pullRequestByHeadMutex.Lock()
	defer fake.pullRequestByHeadMutex.Unlock()
	fake.PullRequestByHeadStub = nil
	fake.pullRequestByHeadReturns = struct {
		result1 *repohost.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestByHeadReturnsOnCall(i int, result1 *repohost.PullRequest, result2 error) {
	fake.pullRequestByHeadMutex.Lock()
	defer fake.pullRequestByHeadMutex.Unlock()
	fake.PullRequestByHeadStub = nil
	if fake.pullRequestByHeadReturnsOnCall == nil {
		fake.pullRequestByHeadReturnsOnCall = make(map[int]struct {
			result1 *repohost.PullRequest
			result2 error
		})
	}
	fake.pullRequestByHeadReturnsOnCall[i] = struct {
		result1 *repohost.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestByNumber(arg1 context.Context, arg2 string, arg3 string, arg4 int) (*repohost.PullRequest, error) {
	fake.pullRequestByNumberMutex.Lock()
	ret, specificReturn := fake.pullRequestByNumberReturnsOnCall[len(fake.pullRequestByNumberArgsForCall)]
	fake.pullRequestByNumberArgsForCall = append(fake.pullRequestByNumberArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.PullRequestByNumberStub
	fakeReturns := fake.pullRequestByNumberReturns
	fake.recordInvocation("PullRequestByNumber", []interface{}{arg1, arg2, arg3, arg4})
	fake.pullRequestByNumberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) PullRequestByNumberCallCount() int {
	fake.pullRequestByNumberMutex.RLock()
	defer fake.pullRequestByNumberMutex.RUnlock()
	return len(fake.pullRequestByNumberArgsForCall)
}

func (fake *FakeRepoHostClient) PullRequestByNumberCalls(stub func(context.Context, string, string, int) (*repohost.PullRequest, error)) {
	fake.pullRequestByNumberMutex.Lock()
	defer fake.pullRequestByNumberMutex.Unlock()
	fake.PullRequestByNumberStub = stub
}

func (fake *FakeRepoHostClient) PullRequestByNumberArgsForCall(i int) (context.Context, string, string, int) {
	fake.pullRequestByNumberMutex.RLock()
	defer fake.pullRequestByNumberMutex.RUnlock()
	argsForCall := fake.pullRequestByNumberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRepoHostClient) PullRequestByNumberReturns(result1 *repohost.PullRequest, result2 error) {
	fake.pullRequestByNumberMutex.Lock()
	defer fake.pullRequestByNumberMutex.Unlock()
	fake.PullRequestByNumberStub = nil
	fake.pullRequestByNumberReturns = struct {
		result1 *repohost.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestByNumberReturnsOnCall(i int, result1 *repohost.PullRequest, result2 error) {
	fake.pullRequestByNumberMutex.Lock()
	defer fake.pullRequestByNumberMutex.Unlock()
	fake.PullRequestByNumberStub = nil
	if fake.pullRequestByNumberReturnsOnCall == nil {
		fake.pullRequestByNumberReturnsOnCall = make(map[int]struct {
			result1 *repohost.PullRequest
			result2 error
		})
	}
	fake.pullRequestByNumberReturnsOnCall[i] = struct {
		result1 *repohost.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestChecks(arg1 context.Context, arg2 string, arg3 string, arg4 int) (repohost.PullRequestCheckRollup, error) {
	fake.pullRequestChecksMutex.Lock()
	ret, specificReturn := fake.pullRequestChecksReturnsOnCall[len(fake.pullRequestChecksArgsForCall)]
	fake.pullRequestChecksArgsForCall = append(fake.pullRequestChecksArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.PullRequestChecksStub
	fakeReturns := fake.pullRequestChecksReturns
	fake.recordInvocation("PullRequestChecks", []interface{}{arg1, arg2, arg3, arg4})
	fake.pullRequestChecksMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) PullRequestChecksCallCount() int {
	fake.pullRequestChecksMutex.RLock()
	defer fake.pullRequestChecksMutex.RUnlock()
	return len(fake.pullRequestChecksArgsForCall)
}

func (fake *FakeRepoHostClient) PullRequestChecksCalls(stub func(context.Context, string, string, int) (repohost.PullRequestCheckRollup, error)) {
	fake.pullRequestChecksMutex.Lock()
	defer fake.pullRequestChecksMutex.Unlock()
	fake.PullRequestChecksStub = stub
}

func (fake *FakeRepoHostClient) PullRequestChecksArgsForCall(i int) (context.Context, string, string, int) {
	fake.pullRequestChecksMutex.RLock()
	defer fake.pullRequestChecksMutex.RUnlock()
	argsForCall := fake.pullRequestChecksArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRepoHostClient) PullRequestChecksReturns(result1 repohost.PullRequestCheckRollup, result2 error) {
	fake.pullRequestChecksMutex.Lock()
	defer fake.pullRequestChecksMutex.Unlock()
	fake.PullRequestChecksStub = nil
	fake.pullRequestChecksReturns = struct {
		result1 repohost.PullRequestCheckRollup
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestChecksReturnsOnCall(i int, result1 repohost.PullRequestCheckRollup, result2 error) {
	fake.pullRequestChecksMutex.Lock()
	defer fake.pullRequestChecksMutex.Unlock()
	fake.PullRequestChecksStub = nil
	if fake.pullRequestChecksReturnsOnCall == nil {
		fake.pullRequestChecksReturnsOnCall = make(map[int]struct {
			result1 repohost.PullRequestCheckRollup
			result2 error
		})
	}
	fake.pullRequestChecksReturnsOnCall[i] = struct {
		result1 repohost.PullRequestCheckRollup
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestReactions(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) (repohost.ReactionPage, error) {
	fake.pullRequestReactionsMutex.Lock()
	ret, specificReturn := fake.pullRequestReactionsReturnsOnCall[len(fake.pullRequestReactionsArgsForCall)]
	fake.pullRequestReactionsArgsForCall = append(fake.pullRequestReactionsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PullRequestReactionsStub
	fakeReturns := fake.pullRequestReactionsReturns
	fake.recordInvocation("PullRequestReactions", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.pullRequestReactionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) PullRequestReactionsCallCount() int {
	fake.pullRequestReactionsMutex.RLock()
	defer fake.pullRequestReactionsMutex.RUnlock()
	return len(fake.pullRequestReactionsArgsForCall)
}

func (fake *FakeRepoHostClient) PullRequestReactionsCalls(stub func(context.Context, string, string, int, string) (repohost.ReactionPage, error)) {
	fake.pullRequestReactionsMutex.Lock()
	defer fake.pullRequestReactionsMutex.Unlock()
	fake.PullRequestReactionsStub = stub
}

func (fake *FakeRepoHostClient) PullRequestReactionsArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.pullRequestReactionsMutex.RLock()
	defer fake.pullRequestReactionsMutex.RUnlock()
	argsForCall := fake.pullRequestReactionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeRepoHostClient) PullRequestReactionsReturns(result1 repohost.ReactionPage, result2 error) {
	fake.pullRequestReactionsMutex.Lock()
	defer fake.pullRequestReactionsMutex.Unlock()
	fake.PullRequestReactionsStub = nil
	fake.pullRequestReactionsReturns = struct {
		result1 repohost.ReactionPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestReactionsReturnsOnCall(i int, result1 repohost.ReactionPage, result2 error) {
	fake.pullRequestReactionsMutex.Lock()
	defer fake.pullRequestReactionsMutex.Unlock()
	fake.PullRequestReactionsStub = nil
	if fake.pullRequestReactionsReturnsOnCall == nil {
		fake.pullRequestReactionsReturnsOnCall = make(map[int]struct {
			result1 repohost.ReactionPage
			result2 error
		})
	}
	fake.pullRequestReactionsReturnsOnCall[i] = struct {
		result1 repohost.ReactionPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestReviewCommentReactions(arg1 context.Context, arg2 string, arg3 string, arg4 int64, arg5 int) (repohost.ReviewCommentReactionPage, error) {
	fake.pullRequestReviewCommentReactionsMutex.Lock()
	ret, specificReturn := fake.pullRequestReviewCommentReactionsReturnsOnCall[len(fake.pullRequestReviewCommentReactionsArgsForCall)]
	fake.pullRequestReviewCommentReactionsArgsForCall = append(fake.pullRequestReviewCommentReactionsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int64
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PullRequestReviewCommentReactionsStub
	fakeReturns := fake.pullRequestReviewCommentReactionsReturns
	fake.recordInvocation("PullRequestReviewCommentReactions", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.pullRequestReviewCommentReactionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) PullRequestReviewCommentReactionsCallCount() int {
	fake.pullRequestReviewCommentReactionsMutex.RLock()
	defer fake.pullRequestReviewCommentReactionsMutex.RUnlock()
	return len(fake.pullRequestReviewCommentReactionsArgsForCall)
}

func (fake *FakeRepoHostClient) PullRequestReviewCommentReactionsCalls(stub func(context.Context, string, string, int64, int) (repohost.ReviewCommentReactionPage, error)) {
	fake.pullRequestReviewCommentReactionsMutex.Lock()
	defer fake.pullRequestReviewCommentReactionsMutex.Unlock()
	fake.PullRequestReviewCommentReactionsStub = stub
}

func (fake *FakeRepoHostClient) PullRequestReviewCommentReactionsArgsForCall(i int) (context.Context, string, string, int64, int) {
	fake.pullRequestReviewCommentReactionsMutex.RLock()
	defer fake.pullRequestReviewCommentReactionsMutex.RUnlock()
	argsForCall := fake.pullRequestReviewCommentReactionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeRepoHostClient) PullRequestReviewCommentReactionsReturns(result1 repohost.ReviewCommentReactionPage, result2 error) {
	fake.pullRequestReviewCommentReactionsMutex.Lock()
	defer fake.pullRequestReviewCommentReactionsMutex.Unlock()
	fake.PullRequestReviewCommentReactionsStub = nil
	fake.pullRequestReviewCommentReactionsReturns = struct {
		result1 repohost.ReviewCommentReactionPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) PullRequestReviewCommentReactionsReturnsOnCall(i int, result1 repohost.ReviewCommentReactionPage, result2 error) {
	fake.pullRequestReviewCommentReactionsMutex.Lock()
	defer fake.pullRequestReviewCommentReactionsMutex.Unlock()
	fake.PullRequestReviewCommentReactionsStub = nil
	if fake.pullRequestReviewCommentReactionsReturnsOnCall == nil {
		fake.pullRequestReviewCommentReactionsReturnsOnCall = make(map[int]struct {
			result1 repohost.ReviewCommentReactionPage
			result2 error
		})
	}
	fake.pullRequestReviewCommentReactionsReturnsOnCall[i] = struct {
		result1 repohost.ReviewCommentReactionPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) ReplyToReviewThread(arg1 context.Context, arg2 string, arg3 string) error {
	fake.replyToReviewThreadMutex.Lock()
	ret, specificReturn := fake.replyToReviewThreadReturnsOnCall[len(fake.replyToReviewThreadArgsForCall)]
	fake.replyToReviewThreadArgsForCall = append(fake.replyToReviewThreadArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReplyToReviewThreadStub
	fakeReturns := fake.replyToReviewThreadReturns
	fake.recordInvocation("ReplyToReviewThread", []interface{}{arg1, arg2, arg3})
	fake.replyToReviewThreadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepoHostClient) ReplyToReviewThreadCallCount() int {
	fake.replyToReviewThreadMutex.RLock()
	defer fake.replyToReviewThreadMutex.RUnlock()
	return len(fake.replyToReviewThreadArgsForCall)
}

func (fake *FakeRepoHostClient) ReplyToReviewThreadCalls(stub func(context.Context, string, string) error) {
	fake.replyToReviewThreadMutex.Lock()
	defer fake.replyToReviewThreadMutex.Unlock()
	fake.ReplyToReviewThreadStub = stub
}

func (fake *FakeRepoHostClient) ReplyToReviewThreadArgsForCall(i int) (context.Context, string, string) {
	fake.replyToReviewThreadMutex.RLock()
	defer fake.replyToReviewThreadMutex.RUnlock()
	argsForCall := fake.replyToReviewThreadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRepoHostClient) ReplyToReviewThreadReturns(result1 error) {
	fake.replyToReviewThreadMutex.Lock()
	defer fake.replyToReviewThreadMutex.Unlock()
	fake.ReplyToReviewThreadStub = nil
	fake.replyToReviewThreadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) ReplyToReviewThreadReturnsOnCall(i int, result1 error) {
	fake.replyToReviewThreadMutex.Lock()
	defer fake.replyToReviewThreadMutex.Unlock()
	fake.ReplyToReviewThreadStub = nil
	if fake.replyToReviewThreadReturnsOnCall == nil {
		fake.replyToReviewThreadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.replyToReviewThreadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) ResolveReviewThread(arg1 context.Context, arg2 string) error {
	fake.resolveReviewThreadMutex.Lock()
	ret, specificReturn := fake.resolveReviewThreadReturnsOnCall[len(fake.resolveReviewThreadArgsForCall)]
	fake.resolveReviewThreadArgsForCall = append(fake.resolveReviewThreadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ResolveReviewThreadStub
	fakeReturns := fake.resolveReviewThreadReturns
	fake.recordInvocation("ResolveReviewThread", []interface{}{arg1, arg2})
	fake.resolveReviewThreadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepoHostClient) ResolveReviewThreadCallCount() int {
	fake.resolveReviewThreadMutex.RLock()
	defer fake.resolveReviewThreadMutex.RUnlock()
	return len(fake.resolveReviewThreadArgsForCall)
}

func (fake *FakeRepoHostClient) ResolveReviewThreadCalls(stub func(context.Context, string) error) {
	fake.resolveReviewThreadMutex.Lock()
	defer fake.resolveReviewThreadMutex.Unlock()
	fake.ResolveReviewThreadStub = stub
}

func (fake *FakeRepoHostClient) ResolveReviewThreadArgsForCall(i int) (context.Context, string) {
	fake.resolveReviewThreadMutex.RLock()
	defer fake.resolveReviewThreadMutex.RUnlock()
	argsForCall := fake.resolveReviewThreadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRepoHostClient) ResolveReviewThreadReturns(result1 error) {
	fake.resolveReviewThreadMutex.Lock()
	defer fake.resolveReviewThreadMutex.Unlock()
	fake.ResolveReviewThreadStub = nil
	fake.resolveReviewThreadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) ResolveReviewThreadReturnsOnCall(i int, result1 error) {
	fake.resolveReviewThreadMutex.Lock()
	defer fake.resolveReviewThreadMutex.Unlock()
	fake.ResolveReviewThreadStub = nil
	if fake.resolveReviewThreadReturnsOnCall == nil {
		fake.resolveReviewThreadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resolveReviewThreadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) ReviewThreadComments(arg1 context.Context, arg2 string, arg3 string) (repohost.ReviewThreadCommentPage, error) {
	fake.reviewThreadCommentsMutex.Lock()
	ret, specificReturn := fake.reviewThreadCommentsReturnsOnCall[len(fake.reviewThreadCommentsArgsForCall)]
	fake.reviewThreadCommentsArgsForCall = append(fake.reviewThreadCommentsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReviewThreadCommentsStub
	fakeReturns := fake.reviewThreadCommentsReturns
	fake.recordInvocation("ReviewThreadComments", []interface{}{arg1, arg2, arg3})
	fake.reviewThreadCommentsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) ReviewThreadCommentsCallCount() int {
	fake.reviewThreadCommentsMutex.RLock()
	defer fake.reviewThreadCommentsMutex.RUnlock()
	return len(fake.reviewThreadCommentsArgsForCall)
}

func (fake *FakeRepoHostClient) ReviewThreadCommentsCalls(stub func(context.Context, string, string) (repohost.ReviewThreadCommentPage, error)) {
	fake.reviewThreadCommentsMutex.Lock()
	defer fake.reviewThreadCommentsMutex.Unlock()
	fake.ReviewThreadCommentsStub = stub
}

func (fake *FakeRepoHostClient) ReviewThreadCommentsArgsForCall(i int) (context.Context, string, string) {
	fake.reviewThreadCommentsMutex.RLock()
	defer fake.reviewThreadCommentsMutex.RUnlock()
	argsForCall := fake.reviewThreadCommentsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRepoHostClient) ReviewThreadCommentsReturns(result1 repohost.ReviewThreadCommentPage, result2 error) {
	fake.reviewThreadCommentsMutex.Lock()
	defer fake.reviewThreadCommentsMutex.Unlock()
	fake.ReviewThreadCommentsStub = nil
	fake.reviewThreadCommentsReturns = struct {
		result1 repohost.ReviewThreadCommentPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) ReviewThreadCommentsReturnsOnCall(i int, result1 repohost.ReviewThreadCommentPage, result2 error) {
	fake.reviewThreadCommentsMutex.Lock()
	defer fake.reviewThreadCommentsMutex.Unlock()
	fake.ReviewThreadCommentsStub = nil
	if fake.reviewThreadCommentsReturnsOnCall == nil {
		fake.reviewThreadCommentsReturnsOnCall = make(map[int]struct {
			result1 repohost.ReviewThreadCommentPage
			result2 error
		})
	}
	fake.reviewThreadCommentsReturnsOnCall[i] = struct {
		result1 repohost.ReviewThreadCommentPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) ReviewThreads(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) (repohost.ReviewThreadPage, error) {
	fake.reviewThreadsMutex.Lock()
	ret, specificReturn := fake.reviewThreadsReturnsOnCall[len(fake.reviewThreadsArgsForCall)]
	fake.reviewThreadsArgsForCall = append(fake.reviewThreadsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ReviewThreadsStub
	fakeReturns := fake.reviewThreadsReturns
	fake.recordInvocation("ReviewThreads", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.reviewThreadsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRepoHostClient) ReviewThreadsCallCount() int {
	fake.reviewThreadsMutex.RLock()
	defer fake.reviewThreadsMutex.RUnlock()
	return len(fake.reviewThreadsArgsForCall)
}

func (fake *FakeRepoHostClient) ReviewThreadsCalls(stub func(context.Context, string, string, int, string) (repohost.ReviewThreadPage, error)) {
	fake.reviewThreadsMutex.Lock()
	defer fake.reviewThreadsMutex.Unlock()
	fake.ReviewThreadsStub = stub
}

func (fake *FakeRepoHostClient) ReviewThreadsArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.reviewThreadsMutex.RLock()
	defer fake.reviewThreadsMutex.RUnlock()
	argsForCall := fake.reviewThreadsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeRepoHostClient) ReviewThreadsReturns(result1 repohost.ReviewThreadPage, result2 error) {
	fake.reviewThreadsMutex.Lock()
	defer fake.reviewThreadsMutex.Unlock()
	fake.ReviewThreadsStub = nil
	fake.reviewThreadsReturns = struct {
		result1 repohost.ReviewThreadPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) ReviewThreadsReturnsOnCall(i int, result1 repohost.ReviewThreadPage, result2 error) {
	fake.reviewThreadsMutex.Lock()
	defer fake.reviewThreadsMutex.Unlock()
	fake.ReviewThreadsStub = nil
	if fake.reviewThreadsReturnsOnCall == nil {
		fake.reviewThreadsReturnsOnCall = make(map[int]struct {
			result1 repohost.ReviewThreadPage
			result2 error
		})
	}
	fake.reviewThreadsReturnsOnCall[i] = struct {
		result1 repohost.ReviewThreadPage
		result2 error
	}{result1, result2}
}

func (fake *FakeRepoHostClient) ValidateAuth(arg1 context.Context) error {
	fake.validateAuthMutex.Lock()
	ret, specificReturn := fake.validateAuthReturnsOnCall[len(fake.validateAuthArgsForCall)]
	fake.validateAuthArgsForCall = append(fake.validateAuthArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateAuthStub
	fakeReturns := fake.validateAuthReturns
	fake.recordInvocation("ValidateAuth", []interface{}{arg1})
	fake.validateAuthMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRepoHostClient) ValidateAuthCallCount() int {
	fake.validateAuthMutex.RLock()
	defer fake.validateAuthMutex.RUnlock()
	return len(fake.validateAuthArgsForCall)
}

func (fake *FakeRepoHostClient) ValidateAuthCalls(stub func(context.Context) error) {
	fake.validateAuthMutex.Lock()
	defer fake.validateAuthMutex.Unlock()
	fake.ValidateAuthStub = stub
}

func (fake *FakeRepoHostClient) ValidateAuthArgsForCall(i int) context.Context {
	fake.validateAuthMutex.RLock()
	defer fake.validateAuthMutex.RUnlock()
	argsForCall := fake.validateAuthArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRepoHostClient) ValidateAuthReturns(result1 error) {
	fake.validateAuthMutex.Lock()
	defer fake.validateAuthMutex.Unlock()
	fake.ValidateAuthStub = nil
	fake.validateAuthReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) ValidateAuthReturnsOnCall(i int, result1 error) {
	fake.validateAuthMutex.Lock()
	defer fake.validateAuthMutex.Unlock()
	fake.ValidateAuthStub = nil
	if fake.validateAuthReturnsOnCall == nil {
		fake.validateAuthReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateAuthReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRepoHostClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRepoHostClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repoops.RepoHostClient = new(FakeRepoHostClient)
