// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/pmenglund/colin/internal/repoops"
)

type FakeGitHubClient struct {
	BranchExistsStub        func(context.Context, string, string, string) (bool, error)
	branchExistsMutex       sync.RWMutex
	branchExistsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	branchExistsReturns struct {
		result1 bool
		result2 error
	}
	branchExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	CreatePullRequestStub        func(context.Context, string, string, repoops.CreatePullRequestInput) (*repoops.GitHubPullRequest, error)
	createPullRequestMutex       sync.RWMutex
	createPullRequestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 repoops.CreatePullRequestInput
	}
	createPullRequestReturns struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}
	createPullRequestReturnsOnCall map[int]struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}
	MergePullRequestStub        func(context.Context, string, string, int, string) error
	mergePullRequestMutex       sync.RWMutex
	mergePullRequestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	mergePullRequestReturns struct {
		result1 error
	}
	mergePullRequestReturnsOnCall map[int]struct {
		result1 error
	}
	PullRequestByHeadStub        func(context.Context, string, string, string, string) (*repoops.GitHubPullRequest, error)
	pullRequestByHeadMutex       sync.RWMutex
	pullRequestByHeadArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	pullRequestByHeadReturns struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}
	pullRequestByHeadReturnsOnCall map[int]struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}
	PullRequestByNumberStub        func(context.Context, string, string, int) (*repoops.GitHubPullRequest, error)
	pullRequestByNumberMutex       sync.RWMutex
	pullRequestByNumberArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	pullRequestByNumberReturns struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}
	pullRequestByNumberReturnsOnCall map[int]struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}
	PullRequestReactionsStub        func(context.Context, string, string, int, string) (repoops.GitHubReactionPage, error)
	pullRequestReactionsMutex       sync.RWMutex
	pullRequestReactionsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	pullRequestReactionsReturns struct {
		result1 repoops.GitHubReactionPage
		result2 error
	}
	pullRequestReactionsReturnsOnCall map[int]struct {
		result1 repoops.GitHubReactionPage
		result2 error
	}
	ReplyToReviewThreadStub        func(context.Context, string, string) error
	replyToReviewThreadMutex       sync.RWMutex
	replyToReviewThreadArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	replyToReviewThreadReturns struct {
		result1 error
	}
	replyToReviewThreadReturnsOnCall map[int]struct {
		result1 error
	}
	ResolveReviewThreadStub        func(context.Context, string) error
	resolveReviewThreadMutex       sync.RWMutex
	resolveReviewThreadArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	resolveReviewThreadReturns struct {
		result1 error
	}
	resolveReviewThreadReturnsOnCall map[int]struct {
		result1 error
	}
	ReviewThreadCommentsStub        func(context.Context, string, string) (repoops.GitHubReviewThreadCommentPage, error)
	reviewThreadCommentsMutex       sync.RWMutex
	reviewThreadCommentsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	reviewThreadCommentsReturns struct {
		result1 repoops.GitHubReviewThreadCommentPage
		result2 error
	}
	reviewThreadCommentsReturnsOnCall map[int]struct {
		result1 repoops.GitHubReviewThreadCommentPage
		result2 error
	}
	ReviewThreadsStub        func(context.Context, string, string, int, string) (repoops.GitHubReviewThreadPage, error)
	reviewThreadsMutex       sync.RWMutex
	reviewThreadsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	reviewThreadsReturns struct {
		result1 repoops.GitHubReviewThreadPage
		result2 error
	}
	reviewThreadsReturnsOnCall map[int]struct {
		result1 repoops.GitHubReviewThreadPage
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitHubClient) BranchExists(arg1 context.Context, arg2 string, arg3 string, arg4 string) (bool, error) {
	fake.branchExistsMutex.Lock()
	ret, specificReturn := fake.branchExistsReturnsOnCall[len(fake.branchExistsArgsForCall)]
	fake.branchExistsArgsForCall = append(fake.branchExistsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.BranchExistsStub
	fakeReturns := fake.branchExistsReturns
	fake.recordInvocation("BranchExists", []interface{}{arg1, arg2, arg3, arg4})
	fake.branchExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitHubClient) BranchExistsCallCount() int {
	fake.branchExistsMutex.RLock()
	defer fake.branchExistsMutex.RUnlock()
	return len(fake.branchExistsArgsForCall)
}

func (fake *FakeGitHubClient) BranchExistsCalls(stub func(context.Context, string, string, string) (bool, error)) {
	fake.branchExistsMutex.Lock()
	defer fake.branchExistsMutex.Unlock()
	fake.BranchExistsStub = stub
}

func (fake *FakeGitHubClient) BranchExistsArgsForCall(i int) (context.Context, string, string, string) {
	fake.branchExistsMutex.RLock()
	defer fake.branchExistsMutex.RUnlock()
	argsForCall := fake.branchExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGitHubClient) BranchExistsReturns(result1 bool, result2 error) {
	fake.branchExistsMutex.Lock()
	defer fake.branchExistsMutex.Unlock()
	fake.BranchExistsStub = nil
	fake.branchExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) BranchExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.branchExistsMutex.Lock()
	defer fake.branchExistsMutex.Unlock()
	fake.BranchExistsStub = nil
	if fake.branchExistsReturnsOnCall == nil {
		fake.branchExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.branchExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) CreatePullRequest(arg1 context.Context, arg2 string, arg3 string, arg4 repoops.CreatePullRequestInput) (*repoops.GitHubPullRequest, error) {
	fake.createPullRequestMutex.Lock()
	ret, specificReturn := fake.createPullRequestReturnsOnCall[len(fake.createPullRequestArgsForCall)]
	fake.createPullRequestArgsForCall = append(fake.createPullRequestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 repoops.CreatePullRequestInput
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreatePullRequestStub
	fakeReturns := fake.createPullRequestReturns
	fake.recordInvocation("CreatePullRequest", []interface{}{arg1, arg2, arg3, arg4})
	fake.createPullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitHubClient) CreatePullRequestCallCount() int {
	fake.createPullRequestMutex.RLock()
	defer fake.createPullRequestMutex.RUnlock()
	return len(fake.createPullRequestArgsForCall)
}

func (fake *FakeGitHubClient) CreatePullRequestCalls(stub func(context.Context, string, string, repoops.CreatePullRequestInput) (*repoops.GitHubPullRequest, error)) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = stub
}

func (fake *FakeGitHubClient) CreatePullRequestArgsForCall(i int) (context.Context, string, string, repoops.CreatePullRequestInput) {
	fake.createPullRequestMutex.RLock()
	defer fake.createPullRequestMutex.RUnlock()
	argsForCall := fake.createPullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGitHubClient) CreatePullRequestReturns(result1 *repoops.GitHubPullRequest, result2 error) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = nil
	fake.createPullRequestReturns = struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) CreatePullRequestReturnsOnCall(i int, result1 *repoops.GitHubPullRequest, result2 error) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = nil
	if fake.createPullRequestReturnsOnCall == nil {
		fake.createPullRequestReturnsOnCall = make(map[int]struct {
			result1 *repoops.GitHubPullRequest
			result2 error
		})
	}
	fake.createPullRequestReturnsOnCall[i] = struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) MergePullRequest(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) error {
	fake.mergePullRequestMutex.Lock()
	ret, specificReturn := fake.mergePullRequestReturnsOnCall[len(fake.mergePullRequestArgsForCall)]
	fake.mergePullRequestArgsForCall = append(fake.mergePullRequestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.MergePullRequestStub
	fakeReturns := fake.mergePullRequestReturns
	fake.recordInvocation("MergePullRequest", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.mergePullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitHubClient) MergePullRequestCallCount() int {
	fake.mergePullRequestMutex.RLock()
	defer fake.mergePullRequestMutex.RUnlock()
	return len(fake.mergePullRequestArgsForCall)
}

func (fake *FakeGitHubClient) MergePullRequestCalls(stub func(context.Context, string, string, int, string) error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = stub
}

func (fake *FakeGitHubClient) MergePullRequestArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.mergePullRequestMutex.RLock()
	defer fake.mergePullRequestMutex.RUnlock()
	argsForCall := fake.mergePullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeGitHubClient) MergePullRequestReturns(result1 error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = nil
	fake.mergePullRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitHubClient) MergePullRequestReturnsOnCall(i int, result1 error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = nil
	if fake.mergePullRequestReturnsOnCall == nil {
		fake.mergePullRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.mergePullRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitHubClient) PullRequestByHead(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) (*repoops.GitHubPullRequest, error) {
	fake.pullRequestByHeadMutex.Lock()
	ret, specificReturn := fake.pullRequestByHeadReturnsOnCall[len(fake.pullRequestByHeadArgsForCall)]
	fake.pullRequestByHeadArgsForCall = append(fake.pullRequestByHeadArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PullRequestByHeadStub
	fakeReturns := fake.pullRequestByHeadReturns
	fake.recordInvocation("PullRequestByHead", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.pullRequestByHeadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitHubClient) PullRequestByHeadCallCount() int {
	fake.pullRequestByHeadMutex.RLock()
	defer fake.pullRequestByHeadMutex.RUnlock()
	return len(fake.pullRequestByHeadArgsForCall)
}

func (fake *FakeGitHubClient) PullRequestByHeadCalls(stub func(context.Context, string, string, string, string) (*repoops.GitHubPullRequest, error)) {
	fake.pullRequestByHeadMutex.Lock()
	defer fake.pullRequestByHeadMutex.Unlock()
	fake.PullRequestByHeadStub = stub
}

func (fake *FakeGitHubClient) PullRequestByHeadArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.pullRequestByHeadMutex.RLock()
	defer fake.pullRequestByHeadMutex.RUnlock()
	argsForCall := fake.pullRequestByHeadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeGitHubClient) PullRequestByHeadReturns(result1 *repoops.GitHubPullRequest, result2 error) {
	fake.pullRequestByHeadMutex.Lock()
	defer fake.pullRequestByHeadMutex.Unlock()
	fake.PullRequestByHeadStub = nil
	fake.pullRequestByHeadReturns = struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) PullRequestByHeadReturnsOnCall(i int, result1 *repoops.GitHubPullRequest, result2 error) {
	fake.pullRequestByHeadMutex.Lock()
	defer fake.pullRequestByHeadMutex.Unlock()
	fake.PullRequestByHeadStub = nil
	if fake.pullRequestByHeadReturnsOnCall == nil {
		fake.pullRequestByHeadReturnsOnCall = make(map[int]struct {
			result1 *repoops.GitHubPullRequest
			result2 error
		})
	}
	fake.pullRequestByHeadReturnsOnCall[i] = struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) PullRequestByNumber(arg1 context.Context, arg2 string, arg3 string, arg4 int) (*repoops.GitHubPullRequest, error) {
	fake.pullRequestByNumberMutex.Lock()
	ret, specificReturn := fake.pullRequestByNumberReturnsOnCall[len(fake.pullRequestByNumberArgsForCall)]
	fake.pullRequestByNumberArgsForCall = append(fake.pullRequestByNumberArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.PullRequestByNumberStub
	fakeReturns := fake.pullRequestByNumberReturns
	fake.recordInvocation("PullRequestByNumber", []interface{}{arg1, arg2, arg3, arg4})
	fake.pullRequestByNumberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitHubClient) PullRequestByNumberCallCount() int {
	fake.pullRequestByNumberMutex.RLock()
	defer fake.pullRequestByNumberMutex.RUnlock()
	return len(fake.pullRequestByNumberArgsForCall)
}

func (fake *FakeGitHubClient) PullRequestByNumberCalls(stub func(context.Context, string, string, int) (*repoops.GitHubPullRequest, error)) {
	fake.pullRequestByNumberMutex.Lock()
	defer fake.pullRequestByNumberMutex.Unlock()
	fake.PullRequestByNumberStub = stub
}

func (fake *FakeGitHubClient) PullRequestByNumberArgsForCall(i int) (context.Context, string, string, int) {
	fake.pullRequestByNumberMutex.RLock()
	defer fake.pullRequestByNumberMutex.RUnlock()
	argsForCall := fake.pullRequestByNumberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGitHubClient) PullRequestByNumberReturns(result1 *repoops.GitHubPullRequest, result2 error) {
	fake.pullRequestByNumberMutex.Lock()
	defer fake.pullRequestByNumberMutex.Unlock()
	fake.PullRequestByNumberStub = nil
	fake.pullRequestByNumberReturns = struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) PullRequestByNumberReturnsOnCall(i int, result1 *repoops.GitHubPullRequest, result2 error) {
	fake.pullRequestByNumberMutex.Lock()
	defer fake.pullRequestByNumberMutex.Unlock()
	fake.PullRequestByNumberStub = nil
	if fake.pullRequestByNumberReturnsOnCall == nil {
		fake.pullRequestByNumberReturnsOnCall = make(map[int]struct {
			result1 *repoops.GitHubPullRequest
			result2 error
		})
	}
	fake.pullRequestByNumberReturnsOnCall[i] = struct {
		result1 *repoops.GitHubPullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) PullRequestReactions(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) (repoops.GitHubReactionPage, error) {
	fake.pullRequestReactionsMutex.Lock()
	ret, specificReturn := fake.pullRequestReactionsReturnsOnCall[len(fake.pullRequestReactionsArgsForCall)]
	fake.pullRequestReactionsArgsForCall = append(fake.pullRequestReactionsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PullRequestReactionsStub
	fakeReturns := fake.pullRequestReactionsReturns
	fake.recordInvocation("PullRequestReactions", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.pullRequestReactionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitHubClient) PullRequestReactionsCallCount() int {
	fake.pullRequestReactionsMutex.RLock()
	defer fake.pullRequestReactionsMutex.RUnlock()
	return len(fake.pullRequestReactionsArgsForCall)
}

func (fake *FakeGitHubClient) PullRequestReactionsCalls(stub func(context.Context, string, string, int, string) (repoops.GitHubReactionPage, error)) {
	fake.pullRequestReactionsMutex.Lock()
	defer fake.pullRequestReactionsMutex.Unlock()
	fake.PullRequestReactionsStub = stub
}

func (fake *FakeGitHubClient) PullRequestReactionsArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.pullRequestReactionsMutex.RLock()
	defer fake.pullRequestReactionsMutex.RUnlock()
	argsForCall := fake.pullRequestReactionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeGitHubClient) PullRequestReactionsReturns(result1 repoops.GitHubReactionPage, result2 error) {
	fake.pullRequestReactionsMutex.Lock()
	defer fake.pullRequestReactionsMutex.Unlock()
	fake.PullRequestReactionsStub = nil
	fake.pullRequestReactionsReturns = struct {
		result1 repoops.GitHubReactionPage
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) PullRequestReactionsReturnsOnCall(i int, result1 repoops.GitHubReactionPage, result2 error) {
	fake.pullRequestReactionsMutex.Lock()
	defer fake.pullRequestReactionsMutex.Unlock()
	fake.PullRequestReactionsStub = nil
	if fake.pullRequestReactionsReturnsOnCall == nil {
		fake.pullRequestReactionsReturnsOnCall = make(map[int]struct {
			result1 repoops.GitHubReactionPage
			result2 error
		})
	}
	fake.pullRequestReactionsReturnsOnCall[i] = struct {
		result1 repoops.GitHubReactionPage
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) ReplyToReviewThread(arg1 context.Context, arg2 string, arg3 string) error {
	fake.replyToReviewThreadMutex.Lock()
	ret, specificReturn := fake.replyToReviewThreadReturnsOnCall[len(fake.replyToReviewThreadArgsForCall)]
	fake.replyToReviewThreadArgsForCall = append(fake.replyToReviewThreadArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReplyToReviewThreadStub
	fakeReturns := fake.replyToReviewThreadReturns
	fake.recordInvocation("ReplyToReviewThread", []interface{}{arg1, arg2, arg3})
	fake.replyToReviewThreadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitHubClient) ReplyToReviewThreadCallCount() int {
	fake.replyToReviewThreadMutex.RLock()
	defer fake.replyToReviewThreadMutex.RUnlock()
	return len(fake.replyToReviewThreadArgsForCall)
}

func (fake *FakeGitHubClient) ReplyToReviewThreadCalls(stub func(context.Context, string, string) error) {
	fake.replyToReviewThreadMutex.Lock()
	defer fake.replyToReviewThreadMutex.Unlock()
	fake.ReplyToReviewThreadStub = stub
}

func (fake *FakeGitHubClient) ReplyToReviewThreadArgsForCall(i int) (context.Context, string, string) {
	fake.replyToReviewThreadMutex.RLock()
	defer fake.replyToReviewThreadMutex.RUnlock()
	argsForCall := fake.replyToReviewThreadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGitHubClient) ReplyToReviewThreadReturns(result1 error) {
	fake.replyToReviewThreadMutex.Lock()
	defer fake.replyToReviewThreadMutex.Unlock()
	fake.ReplyToReviewThreadStub = nil
	fake.replyToReviewThreadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitHubClient) ReplyToReviewThreadReturnsOnCall(i int, result1 error) {
	fake.replyToReviewThreadMutex.Lock()
	defer fake.replyToReviewThreadMutex.Unlock()
	fake.ReplyToReviewThreadStub = nil
	if fake.replyToReviewThreadReturnsOnCall == nil {
		fake.replyToReviewThreadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.replyToReviewThreadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitHubClient) ResolveReviewThread(arg1 context.Context, arg2 string) error {
	fake.resolveReviewThreadMutex.Lock()
	ret, specificReturn := fake.resolveReviewThreadReturnsOnCall[len(fake.resolveReviewThreadArgsForCall)]
	fake.resolveReviewThreadArgsForCall = append(fake.resolveReviewThreadArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ResolveReviewThreadStub
	fakeReturns := fake.resolveReviewThreadReturns
	fake.recordInvocation("ResolveReviewThread", []interface{}{arg1, arg2})
	fake.resolveReviewThreadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeGitHubClient) ResolveReviewThreadCallCount() int {
	fake.resolveReviewThreadMutex.RLock()
	defer fake.resolveReviewThreadMutex.RUnlock()
	return len(fake.resolveReviewThreadArgsForCall)
}

func (fake *FakeGitHubClient) ResolveReviewThreadCalls(stub func(context.Context, string) error) {
	fake.resolveReviewThreadMutex.Lock()
	defer fake.resolveReviewThreadMutex.Unlock()
	fake.ResolveReviewThreadStub = stub
}

func (fake *FakeGitHubClient) ResolveReviewThreadArgsForCall(i int) (context.Context, string) {
	fake.resolveReviewThreadMutex.RLock()
	defer fake.resolveReviewThreadMutex.RUnlock()
	argsForCall := fake.resolveReviewThreadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGitHubClient) ResolveReviewThreadReturns(result1 error) {
	fake.resolveReviewThreadMutex.Lock()
	defer fake.resolveReviewThreadMutex.Unlock()
	fake.ResolveReviewThreadStub = nil
	fake.resolveReviewThreadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitHubClient) ResolveReviewThreadReturnsOnCall(i int, result1 error) {
	fake.resolveReviewThreadMutex.Lock()
	defer fake.resolveReviewThreadMutex.Unlock()
	fake.ResolveReviewThreadStub = nil
	if fake.resolveReviewThreadReturnsOnCall == nil {
		fake.resolveReviewThreadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resolveReviewThreadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitHubClient) ReviewThreadComments(arg1 context.Context, arg2 string, arg3 string) (repoops.GitHubReviewThreadCommentPage, error) {
	fake.reviewThreadCommentsMutex.Lock()
	ret, specificReturn := fake.reviewThreadCommentsReturnsOnCall[len(fake.reviewThreadCommentsArgsForCall)]
	fake.reviewThreadCommentsArgsForCall = append(fake.reviewThreadCommentsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ReviewThreadCommentsStub
	fakeReturns := fake.reviewThreadCommentsReturns
	fake.recordInvocation("ReviewThreadComments", []interface{}{arg1, arg2, arg3})
	fake.reviewThreadCommentsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitHubClient) ReviewThreadCommentsCallCount() int {
	fake.reviewThreadCommentsMutex.RLock()
	defer fake.reviewThreadCommentsMutex.RUnlock()
	return len(fake.reviewThreadCommentsArgsForCall)
}

func (fake *FakeGitHubClient) ReviewThreadCommentsCalls(stub func(context.Context, string, string) (repoops.GitHubReviewThreadCommentPage, error)) {
	fake.reviewThreadCommentsMutex.Lock()
	defer fake.reviewThreadCommentsMutex.Unlock()
	fake.ReviewThreadCommentsStub = stub
}

func (fake *FakeGitHubClient) ReviewThreadCommentsArgsForCall(i int) (context.Context, string, string) {
	fake.reviewThreadCommentsMutex.RLock()
	defer fake.reviewThreadCommentsMutex.RUnlock()
	argsForCall := fake.reviewThreadCommentsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeGitHubClient) ReviewThreadCommentsReturns(result1 repoops.GitHubReviewThreadCommentPage, result2 error) {
	fake.reviewThreadCommentsMutex.Lock()
	defer fake.reviewThreadCommentsMutex.Unlock()
	fake.ReviewThreadCommentsStub = nil
	fake.reviewThreadCommentsReturns = struct {
		result1 repoops.GitHubReviewThreadCommentPage
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) ReviewThreadCommentsReturnsOnCall(i int, result1 repoops.GitHubReviewThreadCommentPage, result2 error) {
	fake.reviewThreadCommentsMutex.Lock()
	defer fake.reviewThreadCommentsMutex.Unlock()
	fake.ReviewThreadCommentsStub = nil
	if fake.reviewThreadCommentsReturnsOnCall == nil {
		fake.reviewThreadCommentsReturnsOnCall = make(map[int]struct {
			result1 repoops.GitHubReviewThreadCommentPage
			result2 error
		})
	}
	fake.reviewThreadCommentsReturnsOnCall[i] = struct {
		result1 repoops.GitHubReviewThreadCommentPage
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) ReviewThreads(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) (repoops.GitHubReviewThreadPage, error) {
	fake.reviewThreadsMutex.Lock()
	ret, specificReturn := fake.reviewThreadsReturnsOnCall[len(fake.reviewThreadsArgsForCall)]
	fake.reviewThreadsArgsForCall = append(fake.reviewThreadsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ReviewThreadsStub
	fakeReturns := fake.reviewThreadsReturns
	fake.recordInvocation("ReviewThreads", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.reviewThreadsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitHubClient) ReviewThreadsCallCount() int {
	fake.reviewThreadsMutex.RLock()
	defer fake.reviewThreadsMutex.RUnlock()
	return len(fake.reviewThreadsArgsForCall)
}

func (fake *FakeGitHubClient) ReviewThreadsCalls(stub func(context.Context, string, string, int, string) (repoops.GitHubReviewThreadPage, error)) {
	fake.reviewThreadsMutex.Lock()
	defer fake.reviewThreadsMutex.Unlock()
	fake.ReviewThreadsStub = stub
}

func (fake *FakeGitHubClient) ReviewThreadsArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.reviewThreadsMutex.RLock()
	defer fake.reviewThreadsMutex.RUnlock()
	argsForCall := fake.reviewThreadsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeGitHubClient) ReviewThreadsReturns(result1 repoops.GitHubReviewThreadPage, result2 error) {
	fake.reviewThreadsMutex.Lock()
	defer fake.reviewThreadsMutex.Unlock()
	fake.ReviewThreadsStub = nil
	fake.reviewThreadsReturns = struct {
		result1 repoops.GitHubReviewThreadPage
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) ReviewThreadsReturnsOnCall(i int, result1 repoops.GitHubReviewThreadPage, result2 error) {
	fake.reviewThreadsMutex.Lock()
	defer fake.reviewThreadsMutex.Unlock()
	fake.ReviewThreadsStub = nil
	if fake.reviewThreadsReturnsOnCall == nil {
		fake.reviewThreadsReturnsOnCall = make(map[int]struct {
			result1 repoops.GitHubReviewThreadPage
			result2 error
		})
	}
	fake.reviewThreadsReturnsOnCall[i] = struct {
		result1 repoops.GitHubReviewThreadPage
		result2 error
	}{result1, result2}
}

func (fake *FakeGitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repoops.GitHubClient = new(FakeGitHubClient)
